-- Migration: Add r2rml_mapping column to projects table
-- Stores W3C R2RML mapping in Turtle syntax generated by LLM
-- Maps data sources (ontology) to physical database schema

ALTER TABLE projects ADD COLUMN IF NOT EXISTS r2rml_mapping TEXT DEFAULT NULL;
